[workspace]
members = ["api", "cli", "core", "server"]
resolver = "3"

[workspace.package]
edition = "2024"
readme = "README.md"
repository = "https://github.com/oblivisheee/ckeylock"
license = "Apache-2.0"
