[package]
name = "ckeylock"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
tokio-tungstenite = "0.26.2"
